language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov

# command to run tests
script:
  - pytest --cov=memocell

after_success:
  - codecov
